server :
  port : 8080
  servlet :
    context-path : '/'



spring :
  profiles :
    # client-secret등 보안문제로 인해, Git 업로드에서 제외할 설정파일을 include해서 사용하도록 함
    include : oauth

  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    url :               'jdbc:mysql://localhost:3306/third'
    username :          root
    password :          root

  jpa :
    hibernate :
      ddl-auto : create-drop

  devtools :
    livereload :
      enabled : true
      port :    35279

  redis :
    host : localhost
    port : 6379

#  session :
#    jdbc :
#      initialize-schema : always
#      table-name :        SPRING_SESSION
#    store-type : jdbc